I5 setup storybook js
maany/rucio-webui-nextjs pull request #9
Opened 2023-02-15 17:36 UTC by ThePhisch

Installed storybook and ported the first story component `Alert`. Installed further dependencies including `@primer/css`, `sass`, `sass-loader` as needed.

2023-02-16 08:58 UTC, maany requested changes
Looks good! If we can avoid using `legacy-peer-deps` it would be best. But for some packages, it is unavoidable.
Also, can we move the stories inside the `src` directory? and rename it to `component-library`?

2023-02-16 08:58 UTC, maany commented on .npmrc
> +legacy-peer-deps=true
what package requires the `legacy-peer-deps` flag to be enabled?

2023-02-16 09:06 UTC, ThePhisch commented on .npmrc
> +legacy-peer-deps=true
I was prompted to add this flag during the installation of `storybook`. It seems to be a [known problem](https://github.com/storybookjs/storybook/issues/18298).

2023-02-16 09:09 UTC, ThePhisch commented
> Also, can we move the stories inside the `src` directory? and rename it to `component-library`?

I will rename `src/stories` to `src/component-library`, as discussed.

2023-02-16 16:54 UTC, maany requested changes
Can we already migrate to Storybook 7
https://chromatic-ui.notion.site/Storybook-7-migration-guide-dbf41fa347304eb2a5e9c69b34503937 

Also, can you refactor the component-library directory to have 2 sub-directories, one for components and one for sass/scss

The components can import from the sass/scss

2023-02-22 10:05 UTC, maany commented
can you rebase?

2023-02-22 10:32 UTC, merged